tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    # Home url
    path('', views.HomeView.as_view(), name='home'),

    # Food
    path('food/', views.food, name='food'),
    path('add_food/', views.add_food, name='add_food'),
    # Edit food or recipe
    path('edit_food/<int:food_id>/', views.edit_food, name='edit_food'),

    # Recipe
    path('add_recipe/', views.add_recipe, name='add_recipe'),

    # Track (records)
    path('track/', views.track, name='track'),
    path('track/<date>/', views.track, name='track_date'),
    path('add_record/<int:section>/', views.add_record, name='add_record'),
]

weight_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
# Internationalization support
from django.conf.urls.i18n import i18n_patterns

# i18n_patterns prepends language code to all URLs
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),

    # hides default language code prefix
    prefix_default_language=False
)

tracker/models.py
from django.db import models
from django.core.exceptions import ValidationError

# context string internationalization support
from django.utils.translation import ugettext_lazy as _

from .managers import RecipeManager

# Relations:
# ForeignKey - M-to-1
# 

# on_delete = What to do with the objects referencing deleting object
# - also delete (CASCADE)
# - restrict deletion (RESTRICT)
# - set reference to NULL (SET NULL)

# blank - can be skipped by the user
# null - can be actually stored in database as NULL not '' or 0
# default - value by default (with blank and null)

# related_name is used to name relation (for use: Parent.<related_name>.all(), child_set)

class Food(models.Model):
    """ General class representing food, used in eaten food records. """
    name = models.CharField(max_length=100, unique=True)
    # calories per 100 gram
    calories = models.FloatField(verbose_name=_("Food calories in 100 gram"))

    class Meta:
        verbose_name = _("Food")
        verbose_name_plural = _("Food")

    def __str__(self):
        return self.name

class Recipe(models.Model):
    """ Recipe - collection of food. Complex & distinct.
    Can consist of one or multiple products. """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    objects = RecipeManager()

    def is_food_alias(self):
        """Determine whether recipe is food/recipe alias."""
        return self.belong_recipe.count() == 1

    @property
    def food_alias(self):
        return self.belong_recipe.first().have_etable

    def __str__(self):
        if self.is_food_alias():
            return str(self.food_alias)

        return self.name

    @property
    def calories(self):
        """ Recipe calories per 100 gram. """
        product_totals = sum([p.total for p in self.belong_recipe.all()])
        product_weights = sum([p.weight for p in self.belong_recipe.all()])
        if product_weights == 0:
            return None
        else:
            return (product_totals / product_weights) * 100


class Product(models.Model):
    """ Some real food (have weight) that is bind to simple/complex
    (from one or multiple products) recipe. """
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='belong_recipe') # child_recipes

    # can't specify all recipe choices without recipe parent
    have_food = models.ForeignKey(Food, on_delete=models.RESTRICT, null=True, blank=True)
    have_recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True, blank=True, related_name='have_recipe') # parent_recipes
    weight = models.FloatField(default=100)

    def clean(self):
        if (
            self.have_food is None
            and self.have_recipe is None
            or self.have_food is not None
            and self.have_recipe is not None
        ):
            raise ValidationError(
                _("Food and recipe references can not be [not] null together.")
            )

    @property
    def have_etable(self):
        """Return Food or Recipe object that product is pointing to."""
        if self.have_food is not None:
            return self.have_food
        
        if self.have_recipe is not None:
            return self.have_recipe

    def __str__(self):
        return f"{self.recipe} - {self.have_etable}"

    @property
    def total(self):
        """Total product calorie value."""
        return (self.weight * self.have_etable.calories) / 100

class Record(models.Model):
    """ Represent eaten food record at some day and day section (zone). """
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, verbose_name="Eaten food")
    # weight choices for ModelForm for form Select widget
    WEIGHT_CHOICES = [
        (10, 10),
        (100, 100),
        (150, 150),
        (200, 200),
        (250, 250),
    ]
    weight = models.FloatField(choices=WEIGHT_CHOICES, verbose_name="Weight of eaten food")
    date_added = models.DateField(auto_now_add=True)
    section = models.IntegerField()

    @property
    def total(self):
        """ Total eaten food calories. """
        return self.weight * self.recipe.calories

    def __str__(self):
        return str(self.recipe)

tracker/forms.py
from django import forms
from .models import Food, Recipe, Product, Record


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'calories']
        labels = {
            'name': 'Food name',
            'calories': 'Food calories (per 100 gram)',
        }


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'description']
        labels = {
            'name': 'Recipe name',
            'description': 'Recipe description',
        }

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['have_recipe', 'weight']
        labels = {
            'have_recipe': 'Food',
            'weight': 'Food weight (in grams)',
        }

    # def __init__(self, *args, **kwargs):
    #     """ Overridden init to get initial product parent. """
    #     super(ProductForm, self).__init__(*args, **kwargs)

    #     # Exclude parent recipe in food Select widget
    #     initial = kwargs.get('initial', None)
    #     if initial is not None:
    #         parent_recipe = initial.get('recipe', None)
    #         if parent_recipe is not None:
    #             # Change choices excluding parent
    #             self.fields['have_recipe'].choices = [(r, str(r))
    #                                                   for r in Recipe.objects.exclude(pk=parent_recipe)]
    #         else:
    #             raise Exception("Initial parent recipe is required! (for proper form widget)")

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['recipe', 'weight']
        labels = {
            'recipe': 'Food eaten',
            'weight': 'Eaten food weight',
        }

ProductFormSet = forms.modelformset_factory(
    Product, fields=['have_recipe', 'weight'], extra=1
)

InlineProductFormSet = forms.inlineformset_factory(
    Recipe, Product, fields=['have_recipe', 'weight'], fk_name='recipe', extra=0
)

tracker/views.py
import datetime
from pprint import pprint

from django.forms import formset_factory, modelformset_factory
from django.http.response import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView

from .forms import (FoodForm, InlineProductFormSet, ProductForm,
                    ProductFormSet, RecipeForm, RecordForm)
from .models import Food, Product, Recipe, Record


class HomeView(TemplateView):
    template_name = "tracker/index.html"


def food(request):
    """ Responds with the table of custom food (recipes). """
    recipes = Recipe.objects.all()
    context = {'recipes': recipes}
    return render(request, 'tracker/food.html', context)


def add_food(request):
    """ Responds with the form to add new food. """
    if request.method == 'GET':
        form = FoodForm()
        context = {'form': form}
        return render(request, 'tracker/add_food.html', context)
    elif request.method == 'POST':
        form = FoodForm(data=request.POST)
        if form.is_valid():
            # Because user will be choosing eaten food from recipes objects
            # we need to create a basic product and recipe objects together
            # with food object so that it can choose them.
            f = form.save()
            r = Recipe.objects.create_food(name=f.name, food=f)
            return redirect('tracker:food')
        else:
            context = {'form': form}
            return render(request, 'tracker/add_food.html', context)
    else:
        raise Exception("Undefined HTTP request method.")


def add_recipe(request):
    """ The add recipe page consist of a recipe name/desc form and a set of product forms. """
    if request.method == 'GET':
        recipe_form = RecipeForm()
        product_formset = ProductFormSet(queryset=Product.objects.none())
        context = {'recipe_form': recipe_form, 'product_formset': product_formset}
        return render(request, 'tracker/add_recipe.html', context)
    elif request.method == 'POST':
        recipe_form = RecipeForm(data=request.POST)
        product_formset = ProductFormSet(data=request.POST)

        # Is recipe form is valid (recipe name and description)
        if recipe_form.is_valid():
            # Is recipe attached products are selected valid
            if product_formset.is_valid():
                recipe_created = recipe_form.save()

                for form in product_formset.forms:
                    # Bind all created products to the form
                    product = form.save(commit=False)
                    product.recipe = recipe_created
                    product.save()

                return redirect(reverse('tracker:food'))
            else:
                return HttpResponseBadRequest("Invalid product forms!")
        else:
            return HttpResponseBadRequest("Invalid recipe form!")


def edit_food(request, food_id):
    r = Recipe.objects.get(pk=food_id)

    # If recipe is food alias => update food
    if r.is_food_alias():
        p = r.belong_recipe.first()
        f = p.have_food

        # The recipe is a discrete
        if request.method == 'GET':
            form = FoodForm(instance=f)
            context = {'form': form, 'food_id': food_id}
            return render(request, 'tracker/edit_food.html', context)
        elif request.method == 'POST':
            form = FoodForm(data=request.POST, instance=f)

            if form.is_valid():
                # Save changes to the food
                form.save()
                return redirect('tracker:food')
            else:
                context = {'form': form, 'food_id': food_id}
                return render(request, 'tracker/edit_food.html', context)
        else:
            raise Exception("Undefined HTTP request method.")

    # Update food as recipe
    return edit_recipe(request, food_id)


def edit_recipe(request, food_id):
    """Patch given recipe with the given request POST data."""

    # Handle changes
    if request.method == "POST":
        recipe = get_object_or_404(Recipe, pk=food_id)
        recipe_form = RecipeForm(data=request.POST, instance=recipe)
        product_formset = InlineProductFormSet(data=request.POST, instance=recipe)
        if recipe_form.is_valid():
            if product_formset.is_valid():
                recipe_form.save()
                product_formset.save()
                return redirect(reverse('tracker:food'))
            else:
                return HttpResponseBadRequest("Invalid product formset data.")
        else:
            return HttpResponseBadRequest("Invalid recipe form data.")

    # Render form
    recipe = get_object_or_404(Recipe, pk=food_id)
    recipe_form = RecipeForm(instance=recipe)
    product_formset = InlineProductFormSet(instance=recipe)
    context = {
        'recipe_form': recipe_form,
        'product_formset': product_formset,
        'food_id': food_id,
    }
    return render(request, 'tracker/edit_recipe.html', context)


def track(request, date = None):
    # Redirect to the same URL with current date
    if date is None:
        cur_date = datetime.datetime.now() + datetime.timedelta(hours=3)
        return redirect(f'/track/{cur_date.date()}/')

    # Convert date string to date object
    date = datetime.datetime.strptime(date, '%Y-%m-%d').date()

    # 1. Make all computations (prepare for template usage)
    # 2. Use/iterate all prepared data
    section_names = ['breakfast', 'second breakfast', 'dinner', 'lunch', 'supper']
    sections_records = [Record.objects.filter(date_added=date, section=i) for i in range(1, 6)]
    section_totals = [sum([record.total for record in records])
                      for records in sections_records]
    total = sum(section_totals)

    context = {'sections': zip(section_names, section_totals, sections_records, range(1, 6)),
               'total': total,
               'track_date': date}
    return render(request, 'tracker/track.html', context)


def add_record(request, section):
    if request.method == 'GET':
        form = RecordForm()
        context = {'form': form, 'section': section}
        return render(request, 'tracker/add_record.html', context)
    elif request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            added_record = form.save(commit=False)
            added_record.section = section
            added_record.save()
            return redirect('tracker:track')
        else:
            context = {'form': form}
            return render(request, 'tracker/add_record.html', context)
    else:
        raise Exception("Undefined HTTP request method.")

tracker/templates/tracker/add_food.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block header %}
Add food
{% endblock %}

{% block content %}

<form action="{% url 'tracker:add_food' %}" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" name="Submit">Add food</button>
</form>

{% endblock %}

tracker/templates/tracker/add_recipe.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block header %}
  Create recipe
{% endblock %}

{% block content %}

  <form id="form-container" method="POST">
    {% csrf_token %}

    {# Recipe name/desc #}
    {{ recipe_form|crispy }}

    {# Managment form, provides hidden info fields (total, max, min, ...) #}
    {{ product_formset.management_form }}

    {# Recipe added products #}
    {% for product_form in product_formset %}
      <div class="product-form">
        {{ product_form|crispy }}
      </div>
    {% endfor %}

    <button id="add-form" type="button">Add another form</button>
    <button class="btn btn-primary" type="submit">Add products</button>
  </form>
  
  <script>
    // Dynamic form adding
    let productForms = document.querySelectorAll(".product-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = productForms.length - 1

    addButton.addEventListener('click', addForm)
    function addForm(e) {
      e.preventDefault()

      formNum++
      let newForm = productForms[0].cloneNode(true)
      newForm.innerHTML = newForm.innerHTML.replace(RegExp(`form-(\\d){1}-`, 'g'), `form-${formNum}-`)

      container.insertBefore(newForm, addButton)
      totalForms.setAttribute('value', `${formNum+1}`)
    }
  </script>

{% endblock %}

tracker/templates/tracker/add_record.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block header %}
  Add new record
{% endblock %}

{% block content %}
  <form action="{% url 'tracker:add_record' section %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" name="Submit">Add record</button>
  </form>
{% endblock %}

tracker/templates/tracker/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>Weight tracker</title>
  </head>
  <body>
    <div class="container py-2">
      <h1>
        {% block header %}{% endblock header %}
      </h1>
      <hr>
      <p>
        {% block content %}{% endblock content%}
      </p>
    </div>
  </body>
</html>

tracker/templates/tracker/edit_food.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block header %}
  Edit food object
{% endblock header %}

{% block content %}
  <form action="{% url 'tracker:edit_food' food_id %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-primary" type="submit" name="submit">Save changes</button>
  </form>
{% endblock %}

tracker/templates/tracker/edit_recipe.html
{% extends "tracker/base.html" %}
{% load crispy_forms_tags %}

{% block header %}
Edit recipe
{% endblock %}

{% block content %}


<form action="{% url 'tracker:edit_food' food_id %}" method="POST">
  {% csrf_token %}

  {{ recipe_form|crispy }}

  <h3>Food containing in recipe:</h3>

  {{ product_formset.management_form }}
  {% for product_form in product_formset %}
    <div class="mb-4">
      {{ product_form|crispy }}
    </div>
  {% empty %}
    <p>No products in the recipe.</p>
  {% endfor %}

  <input class="btn btn-primary" type="submit" value="Save changes"> <br>
</form>

{% endblock %}

tracker/templates/tracker/food.html
{% extends "tracker/base.html" %}

{% block header %}
Your food:
{% endblock %}

{% block content %}

<table>
  {# Header #}
  <tr>
    <th>Food<br><a href="#">sort</a></th>
    <th>Calories/100g<br><a href="#">sort</a></th>
    <!-- <th></th> -->
  </tr>
  {# Food #}
  {% for recipe in recipes %}
    <tr>
      <td>{{ recipe }}</td>
      <td style="text-align: center;">{{ recipe.calories|floatformat }}</td>
      <td><a href="{% url 'tracker:edit_food' recipe.id %}">edit</a> | delete</td>
    </tr>
  {% empty %}
    <tr>
      <td colspan="3">
        No food created
      </td>
    </tr>
  {% endfor %}
</table>

<p class="my-3">
  <a href="{% url 'tracker:add_food' %}">Add food</a> -
  <a href="{% url 'tracker:add_recipe' %}">Add recipe</a> (collection of food)
</p>

{% endblock %}

tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}

{% block header %}
    Welcome to the weight tracker!
{% endblock %}
{% block content %}
    Weight tracker will help you to track your body weight and eaten food. Just add some <a href="{% url 'tracker:food' %}">food</a> to the table and click <a href="{% url 'tracker:track' %}">track</a> and start tracking right now.
{% endblock %}

tracker/templates/tracker/track.html
{% extends "tracker/base.html" %}

{% block header %} Track your diet on {{ track_date|date:"j F Y" }} {% endblock %}

{% block content %}
Yesterday - Tommorow
  {% for name, total, records, n in sections %}
    <h2>{{ name|capfirst }}</h2>
    <ul class="bm-2">
      {% for record in records %}
        <li>
          <b>{{ record|capfirst }}</b>, {{ record.weight|floatformat }} gram<br>
          = {{ record.total|floatformat }} calories
        </li>
      {% empty %}
        You have no record.
      {% endfor %}
      <p><a class="btn btn-outline-secondary mt-2" href="{% url 'tracker:add_record' n %}">Add record</a></p>
    </ul>
    {% if total > 1 %}
      <p><b>Section total</b>: {{ total|floatformat }} calories</p>
    {% endif %}

  {% endfor%}

  <hr>
  <h3>Day total: {{ total|floatformat:0 }} calories</h3>

{% endblock content %}

tracker/templates/tracker/view_recipe.html
{% extends "tracker/base.html" %}

{% block header %}
  Recipe product list:
{% endblock header %}

{% block content %}
  {% for p in products %}
    <p>{{ p }}</p>
  {% endfor %}

  <p><a href="{% url 'tracker:add_product' recipe_pk %}">Add product to the recipe</a></p>

{% endblock content %}